# src/privacy_hud/runtime_contract.py
"""The runtime identity contract (#66): which build is running, which build
was selected, and whether the code actually imported is that build.

Three facts, kept apart because each fails differently:

* **Build identity** (`RuntimeIdentity`, `load_identity`). A bundle carries
  `runtime-build.json`, generated by `scripts/build-runtime-manifest.py`.
  Its `build_id` is a SHA-256 over the bundle's covered files, so two
  bundles that both say "0.8.0" but differ by one byte are different builds.
  The digest is recomputed on load; the manifest's own claim is never
  trusted on its own.
* **Selection** (`Activation`, `load_activation`). Receipt v2
  (`$PLUGIN_DATA/runtime.json`) names the selected bundle, its build, the
  interpreter that supplies dependencies, and an activation epoch. Receipt
  v1 is accepted only as repair input; its `pythonpath` never selects
  application code.
* **Origin** (`verify_import_origins`). Every imported `privacy_hud` module
  must come from the selected bundle's `src`, never from an installed
  distribution, an editable install, or an inherited `PYTHONPATH`.

Stdlib only, and it imports nothing from this package: `scripts/runtime.py`
loads this file by path, before any first-party import has happened, to
decide which code may be imported at all.

I1: nothing here reads or records hook content. Refusals carry a fixed
`FailureCode`, never exception text or file contents.
"""
from __future__ import annotations

import hashlib
import json
import math
import os
import re
import stat
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Literal, TypeAlias

JSONValue: TypeAlias = (
    None | bool | int | float | str
    | list["JSONValue"] | dict[str, "JSONValue"]
)
JSONObject: TypeAlias = dict[str, JSONValue]

FailureCode = Literal[
    "setup_missing", "bundle_invalid", "dependencies_unusable",
    "runtime_mismatch", "runtime_starting", "ledger_unsupported",
    "transition_incomplete", "holder_unknown", "request_failed",
]

# --------------------------------------------------------------------- #
# the build this source tree declares
# --------------------------------------------------------------------- #

#: The release this bundle is. `runtime-build.json` repeats it, and the
#: manifest builder takes it from here.
RELEASE = "0.10.0"

#: Socket envelope version (`"v"` on every frame). Protocol 1 clients are
#: refused; see `daemon._Handler`.
PROTOCOL_VERSION = 2

#: Storage layout generation. Separate from `PRAGMA user_version`, the
#: accounting schema and the snapshot version.
STORAGE_GENERATION = 1

#: Ledger `user_version` values this build reads and writes. Generation
#: 5402 requires the activated-accounting implementation introduced in
#: Privacy HUD 0.9.0. A live client must also match the selected runtime
#: build and activation epoch.
READABLE_SCHEMAS: tuple[int, ...] = (0, 5401, 5402)
WRITABLE_SCHEMAS: tuple[int, ...] = (0, 5401, 5402)

#: HUD snapshot versions this build publishes. Snapshot v3 does not exist.
SNAPSHOT_VERSIONS: tuple[int, ...] = (2,)

MANIFEST_NAME = "runtime-build.json"
MANIFEST_FORMAT = 1
MANIFEST_FIELDS = frozenset({
    "format", "release", "build_id", "protocol", "storage_generation",
    "readable_schemas", "writable_schemas", "snapshot_versions",
})

#: Covered by the build digest: every file under these directories ...
COVERED_TREES: tuple[str, ...] = ("src/privacy_hud", "hooks", "mcp", "ui")
#: ... plus these single files.
COVERED_FILES: tuple[str, ...] = (
    "scripts/runtime.py", "install.sh", ".codex-plugin/plugin.json",
    "pyproject.toml",
)
#: Never covered: caches and bytecode. An unexpected *source* file is
#: covered, so it changes the digest.
_EXCLUDED_DIRS = frozenset({"__pycache__", ".pytest_cache", ".mypy_cache",
                            ".ruff_cache", "node_modules"})
_EXCLUDED_NAMES = frozenset({".DS_Store"})
_DIGEST_DOMAIN = b"privacy-hud-runtime-build\x00"

# --------------------------------------------------------------------- #
# receipt v2
# --------------------------------------------------------------------- #

RECEIPT_NAME = "runtime.json"
RECEIPT_VERSION = 2
LEGACY_RECEIPT_VERSION = 1
RECEIPT_FIELDS = frozenset({
    "v", "python", "env", "dependency_probe", "selected_bundle_root",
    "selected_build_id", "activation_epoch", "storage_generation",
    "recorded_at",
})
#: The existing allowlisted cache settings (`runtime.PINNED_ENV_NAMES`).
PINNED_ENV_NAMES = ("HF_HOME", "HF_HUB_CACHE", "TRANSFORMERS_CACHE")
_MAX_RECEIPT_BYTES = 64 * 1024
_MAX_MANIFEST_BYTES = 16 * 1024

_BUILD_ID = re.compile(r"[0-9a-f]{64}")
_EPOCH = re.compile(r"[0-9a-f]{32}")


@dataclass(frozen=True)
class RuntimeIdentity:
    release: str
    build_id: str
    protocol: int
    storage_generation: int
    readable_schemas: tuple[int, ...]
    writable_schemas: tuple[int, ...]
    snapshot_versions: tuple[int, ...]


@dataclass(frozen=True)
class Activation:
    identity: RuntimeIdentity
    epoch: str
    bundle_root: Path
    python: Path


class RuntimeRefusal(RuntimeError):
    """A fixed-code refusal. The message is the code and nothing else: an
    exception message is a string this plugin did not choose (I1)."""

    code: FailureCode

    def __init__(self, code: FailureCode) -> None:
        super().__init__(code)
        self.code = code


def is_int(value: object) -> bool:
    """An integer that is not a boolean. `True == 1` in Python, and a
    version field must not accept `true`."""
    return isinstance(value, int) and not isinstance(value, bool)


def is_build_id(value: object) -> bool:
    return isinstance(value, str) and _BUILD_ID.fullmatch(value) is not None


def is_epoch(value: object) -> bool:
    return isinstance(value, str) and _EPOCH.fullmatch(value) is not None


# --------------------------------------------------------------------- #
# the digest
# --------------------------------------------------------------------- #

def covered_files(bundle_root: Path) -> list[str]:
    """Relative POSIX paths of every covered file that exists, sorted.

    A missing single file is simply absent from the list, which changes the
    digest. A symlink anywhere in the covered set is refused: a covered path
    must describe bytes inside the bundle, not wherever a link points.
    """
    root = Path(bundle_root)
    found: set[str] = set()
    for tree in COVERED_TREES:
        base = root / tree
        if base.is_symlink():
            raise RuntimeRefusal("bundle_invalid")
        if not base.is_dir():
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = sorted(d for d in dirnames if d not in _EXCLUDED_DIRS)
            for name in dirnames:
                if (Path(dirpath) / name).is_symlink():
                    raise RuntimeRefusal("bundle_invalid")
            for name in filenames:
                if name in _EXCLUDED_NAMES:
                    continue
                path = Path(dirpath) / name
                if path.is_symlink() or not path.is_file():
                    raise RuntimeRefusal("bundle_invalid")
                found.add(path.relative_to(root).as_posix())
    for rel in COVERED_FILES:
        path = root / rel
        if path.is_symlink():
            raise RuntimeRefusal("bundle_invalid")
        if path.is_file():
            found.add(rel)
    return sorted(found)


def _manifest_metadata() -> JSONObject:
    """The manifest fields other than `build_id`, as this source declares
    them. Folded into the digest so a manifest whose release or capability
    lists were edited no longer matches its own `build_id`."""
    return {
        "format": MANIFEST_FORMAT,
        "release": RELEASE,
        "protocol": PROTOCOL_VERSION,
        "storage_generation": STORAGE_GENERATION,
        "readable_schemas": list(READABLE_SCHEMAS),
        "writable_schemas": list(WRITABLE_SCHEMAS),
        "snapshot_versions": list(SNAPSHOT_VERSIONS),
    }


def _frame(digest, data: bytes) -> None:
    digest.update(len(data).to_bytes(8, "big"))
    digest.update(data)


def compute_build_id(bundle_root: Path,
                     metadata: JSONObject | None = None) -> str:
    """SHA-256 over the manifest metadata, then each covered file's sorted
    relative path and bytes, every field length-framed."""
    root = Path(bundle_root)
    meta = _manifest_metadata() if metadata is None else metadata
    digest = hashlib.sha256(_DIGEST_DOMAIN)
    _frame(digest, json.dumps(meta, sort_keys=True,
                              separators=(",", ":")).encode("utf-8"))
    for rel in covered_files(root):
        _frame(digest, rel.encode("utf-8"))
        try:
            _frame(digest, (root / rel).read_bytes())
        except OSError:
            raise RuntimeRefusal("bundle_invalid") from None
    return digest.hexdigest()


def build_manifest(bundle_root: Path) -> JSONObject:
    """The manifest this source tree declares for `bundle_root`."""
    manifest = _manifest_metadata()
    manifest["build_id"] = compute_build_id(bundle_root)
    return manifest


def render_manifest(manifest: JSONObject) -> str:
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


# --------------------------------------------------------------------- #
# loading
# --------------------------------------------------------------------- #

def _int_list(value: object) -> tuple[int, ...] | None:
    if not isinstance(value, list) or not all(is_int(v) for v in value):
        return None
    return tuple(value)


def load_identity(bundle_root: Path) -> RuntimeIdentity:
    """Read and verify `bundle_root/runtime-build.json`.

    Raises `RuntimeRefusal("bundle_invalid")` for an absent, malformed or
    stale manifest, including a bundle whose files no longer hash to the
    recorded `build_id` (a same-release edit, a missing file, an extra
    source file).
    """
    root = Path(bundle_root)
    try:
        raw = (root / MANIFEST_NAME).read_bytes()
    except OSError:
        raise RuntimeRefusal("bundle_invalid") from None
    if len(raw) > _MAX_MANIFEST_BYTES:
        raise RuntimeRefusal("bundle_invalid")
    try:
        manifest = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, ValueError):
        raise RuntimeRefusal("bundle_invalid") from None
    if not isinstance(manifest, dict) or set(manifest) != MANIFEST_FIELDS:
        raise RuntimeRefusal("bundle_invalid")
    release = manifest["release"]
    build_id = manifest["build_id"]
    readable = _int_list(manifest["readable_schemas"])
    writable = _int_list(manifest["writable_schemas"])
    snapshots = _int_list(manifest["snapshot_versions"])
    if (manifest["format"] != MANIFEST_FORMAT
            or not is_int(manifest["format"])
            or not isinstance(release, str) or not release
            or not is_build_id(build_id)
            or not is_int(manifest["protocol"])
            or not is_int(manifest["storage_generation"])
            or readable is None or writable is None or snapshots is None):
        raise RuntimeRefusal("bundle_invalid")
    metadata = {k: v for k, v in manifest.items() if k != "build_id"}
    if compute_build_id(root, metadata) != build_id:
        raise RuntimeRefusal("bundle_invalid")
    return RuntimeIdentity(
        release=release, build_id=build_id,
        protocol=manifest["protocol"],
        storage_generation=manifest["storage_generation"],
        readable_schemas=readable, writable_schemas=writable,
        snapshot_versions=snapshots)


def _receipt_bytes(data_dir: Path) -> tuple[str, bytes]:
    """`("absent"|"unreadable"|"ok", raw)` for the receipt in `data_dir`.

    The three answers are kept apart here, once, so that every caller
    above can decide what each one means rather than inheriting one
    flattened "missing" (#66 Pair 5). `fstat` on the open descriptor and
    `O_NOFOLLOW`: the check has to describe the bytes actually read,
    because this file names a program a hook will execute.
    """
    path = Path(data_dir) / RECEIPT_NAME
    flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
    try:
        fd = os.open(path, flags)
    except FileNotFoundError:
        return "absent", b""
    except OSError:
        return "unreadable", b""
    try:
        info = os.fstat(fd)
        if (not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid()
                or info.st_mode & 0o022
                or info.st_size > _MAX_RECEIPT_BYTES):
            return "unreadable", b""
        with os.fdopen(fd, "rb", closefd=False) as handle:
            raw = handle.read(_MAX_RECEIPT_BYTES + 1)
    except OSError:
        return "unreadable", b""
    finally:
        os.close(fd)
    return "ok", raw


def read_receipt(data_dir: Path) -> JSONObject:
    """The receipt's JSON object, read only if this user owns it and nobody
    else can write it. Raises `RuntimeRefusal("setup_missing")` otherwise.
    """
    state, raw = _receipt_bytes(data_dir)
    if state != "ok":
        raise RuntimeRefusal("setup_missing")
    try:
        receipt = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, ValueError):
        raise RuntimeRefusal("setup_missing") from None
    if not isinstance(receipt, dict):
        raise RuntimeRefusal("setup_missing")
    return receipt


def _valid_receipt_v2(receipt: JSONObject) -> bool:
    if set(receipt) != RECEIPT_FIELDS:
        return False
    if not is_int(receipt["v"]) or receipt["v"] != RECEIPT_VERSION:
        return False
    python = receipt["python"]
    root = receipt["selected_bundle_root"]
    if not isinstance(python, str) or not os.path.isabs(python):
        return False
    if not isinstance(root, str) or not os.path.isabs(root):
        return False
    env = receipt["env"]
    if not isinstance(env, dict) or not all(
            k in PINNED_ENV_NAMES and isinstance(v, str)
            for k, v in env.items()):
        return False
    probe = receipt["dependency_probe"]
    if not isinstance(probe, dict) or not all(
            isinstance(v, (str, bool)) or v is None for v in probe.values()):
        return False
    if not is_build_id(receipt["selected_build_id"]):
        return False
    if not is_epoch(receipt["activation_epoch"]):
        return False
    if (not is_int(receipt["storage_generation"])
            or receipt["storage_generation"] != STORAGE_GENERATION):
        return False
    recorded = receipt["recorded_at"]
    if (isinstance(recorded, bool) or not isinstance(recorded, (int, float))
            or not math.isfinite(recorded) or recorded < 0):
        return False
    return True


#: What `classify_receipt` can answer. Five states, not two: "there is no
#: receipt" and "there is one nobody can read" are different facts, and
#: collapsing them is what would let an unreadable receipt become
#: permission to activate (#66 Pair 5).
ReceiptState = Literal["absent", "unreadable", "malformed", "v1", "v2"]


def _valid_receipt_v1(receipt: JSONObject) -> bool:
    """The historical receipt, checked only as far as repair uses it: a
    version and an absolute interpreter path. Its `pythonpath` is
    deliberately not consulted — receipt v1 never selects application
    code (#66)."""
    if not is_int(receipt.get("v")) or receipt["v"] != LEGACY_RECEIPT_VERSION:
        return False
    python = receipt.get("python")
    return isinstance(python, str) and os.path.isabs(python)


def classify_receipt(data_dir: Path) -> ReceiptState:
    """Name the receipt's state in `data_dir` without deciding anything.

    * `absent` — no file at the receipt's pathname.
    * `unreadable` — a file exists, but not one this process may trust:
      a symlink, another user's, one others can write, too large, or
      undecodable.
    * `malformed` — readable, but not a receipt: not a JSON object, no
      recognized `v`, or a body that fails its own version's validation.
    * `v1` — a well-formed historical receipt. Repair input only.
    * `v2` — a well-formed current receipt.
    """
    state, raw = _receipt_bytes(data_dir)
    if state != "ok":
        return "absent" if state == "absent" else "unreadable"
    try:
        receipt = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, ValueError):
        return "malformed"
    if not isinstance(receipt, dict):
        return "malformed"
    if _valid_receipt_v2(receipt):
        return "v2"
    if _valid_receipt_v1(receipt):
        return "v1"
    return "malformed"


def load_activation(data_dir: Path) -> Activation:
    """The selected runtime, from receipt v2, with the selected bundle's
    identity verified against its files.

    * no receipt, an unreadable or unsafe one, receipt v1 (repair input
      only), or a malformed v2 -> `setup_missing`;
    * a recorded interpreter that is not an executable file ->
      `setup_missing`;
    * a selected bundle whose files do not match its manifest ->
      `bundle_invalid`;
    * a selected bundle whose build is not the recorded build ->
      `runtime_mismatch`.
    """
    receipt = read_receipt(data_dir)
    if not _valid_receipt_v2(receipt):
        raise RuntimeRefusal("setup_missing")
    python = str(receipt["python"])
    if not os.path.isfile(python) or not os.access(python, os.X_OK):
        raise RuntimeRefusal("setup_missing")
    bundle_root = Path(str(receipt["selected_bundle_root"]))
    identity = load_identity(bundle_root)
    if (identity.build_id != receipt["selected_build_id"]
            or identity.storage_generation != STORAGE_GENERATION):
        raise RuntimeRefusal("runtime_mismatch")
    return Activation(identity=identity, epoch=str(receipt["activation_epoch"]),
                      bundle_root=bundle_root, python=Path(python))


def verify_import_origins(bundle_root: Path) -> None:
    """Every loaded `privacy_hud` module must be a file under
    `bundle_root/src/privacy_hud`, and the package's search path must be
    exactly that directory. Raises `RuntimeRefusal("bundle_invalid")`.

    Distribution metadata is never consulted: an installed `privacy-hud`
    distribution is not evidence of which code is running.
    """
    package_dir = (Path(bundle_root) / "src" / "privacy_hud").resolve()
    package = sys.modules.get("privacy_hud")
    if package is None:
        raise RuntimeRefusal("bundle_invalid")
    search = [Path(p).resolve() for p in getattr(package, "__path__", [])]
    if search != [package_dir]:
        raise RuntimeRefusal("bundle_invalid")
    for name, module in list(sys.modules.items()):
        if name != "privacy_hud" and not name.startswith("privacy_hud."):
            continue
        origin = getattr(module, "__file__", None)
        if not isinstance(origin, str):
            raise RuntimeRefusal("bundle_invalid")
        resolved = Path(origin).resolve()
        if not resolved.is_relative_to(package_dir):
            raise RuntimeRefusal("bundle_invalid")
